Quentin - DB classes
QuentCov/MovieManager pull request #85
Opened 2018-02-16 07:12 UTC by QuentCov

2018-02-22 15:09 UTC, DavidCao22 requested changes

2018-02-22 15:09 UTC, DavidCao22 commented on src/data/CreditCardsDB.java
> +		return getCreditCard(creditCard.getCardNumber());
Not sure what this does since it gets a CreditCard and returns a CreditCard.

2018-02-22 15:09 UTC, DavidCao22 commented on src/data/MovieDB.java
> +		return getMovie(movie.getName());
Shouldn't this return the User? Also, there's no User property on a Movie

2018-02-22 15:09 UTC, DavidCao22 commented on src/data/MovieDB.java
> +				createMovie(rs);
Shouldn't this return the Movie object?

2018-02-22 15:09 UTC, DavidCao22 commented on src/data/MovieShowingDB.java
> +			    createMovieShowing(rs);
needs to return the ArrayList

2018-02-22 15:09 UTC, DavidCao22 commented on src/data/OrdersDB.java
> +		return getOrder(order.getCustomer().getEmailAddress());
Isn't this also getting an Order as a param and returning the same Order?

2018-02-22 15:09 UTC, DavidCao22 commented on src/data/TheatresDB.java
> +		return getTheatre(theatre.getName());
Isn't this getting a Theatre object as a param and returning the same one?

2018-02-22 15:09 UTC, DavidCao22 commented on src/data/UserDB.java
> +			    createUser(rs);
Needs to return the User

2018-02-22 15:09 UTC, DavidCao22 commented on src/data/UserDB.java
> +			    createUser(rs);
Needs to return the User

2018-02-22 15:09 UTC, DavidCao22 commented on src/data/UserDB.java
> +		return getUser(user.getEmailAddress());
Isn't this getting a User object as a param and returning the same object?

2018-02-22 15:09 UTC, DavidCao22 commented on src/models/User.java
> +		super();
Do we need to add this?

2018-02-24 20:34 UTC, QuentCov commented on src/models/User.java
> +		super();
JavaBeans need an empty constructor.

2018-02-24 20:34 UTC, QuentCov commented
That should be all the changes

2018-02-25 00:08 UTC, DavidCao22 approved these changes

2018-02-25 00:08 UTC, merged

2018-02-25 00:08 UTC, DavidCao22 commented
Looks good to me.